name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GREETINGS_TOKEN }}
        issue-message: "Oh, so you have issues ? Nvm, we all have."
        pr-message: "Kaaj nei ?"
